server:
  port: 8081

spring:
  profiles:
    - local
    - alpah
  webflux:
    base-path: /api/v1
  data:
    mongodb:
      uri: mongodb://eve2020:dlqmtjqltm2020!@eve-docdb.cluster-cgfa9kmhzbh9.ap-northeast-1.docdb.amazonaws.com:27017/?ssl=true&ssl_ca_certs=rds-combined-ca-bundle.pem&replicaSet=rs0&readPreference=secondaryPreferred&retryWrites=false
      port: 27017
      username: eve2020
      password:
        - dlqmtjqltm2020!
  zipkin:
    base-url: https://eve.nexonpromo.com
  sleuth:
    web:
      skip-pattern: (/ping)
    sampler:
      probability: 1.0
---
spring:
  profiles:
    - qa

---
spring:
  profiles:
    - pre

---
spring:
  profiles:
    - live